# docker-compose.yml
version: '2.8'
services:
  ctmsmw:
    build: .
    image: belivipro9x99/ctmsmw
    container_name: "ctmsmw"
    user: root
    restart: always
    environment:
      PORT: 22075
    volumes:
      - /shared:/shared
    ports:
      - 22075:22075