# docker-compose.yml
version: '2.8'
services:
  ctmsmw:
    build: .
    container_name: "ctmsmw"
    user: root
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      PORT: 22075
      FORCE_COLOR: 1
    volumes:
      - /shared:/shared
    ports:
      - 22075:22075